/* Банки вопросов для всех игр. Чтобы добавить вопрос — копируй формат соседнего. */
window.DATA = {

/* ───────── 1. Угадай вывод ─────────
   c — код, a — правильный вывод, w — 3 неправильных, why — объяснение */
predict: [
{ c: 'console.log(typeof null);', a: 'object', w: ['null', 'undefined', 'number'],
  why: 'Это историческая ошибка языка: typeof null возвращает "object". Чтобы проверить на null, пиши x === null.' },
{ c: 'console.log("5" + 3);', a: '53', w: ['8', 'NaN', '"8"'],
  why: 'Если у плюса хотя бы одна сторона — строка, он склеивает. Число 3 превращается в "3".' },
{ c: 'console.log("5" - 3);', a: '2', w: ['53', 'NaN', '8'],
  why: 'Минус умеет только считать, поэтому строка "5" превращается в число 5.' },
{ c: 'console.log(0.1 + 0.2 === 0.3);', a: 'false', w: ['true', '0.3', 'NaN'],
  why: 'Дробные числа хранятся неточно: 0.1 + 0.2 = 0.30000000000000004. Деньги лучше считать в копейках (целых числах).' },
{ c: 'const a = [1, 2, 3];\nconsole.log(a.length);\na.push(4);\nconsole.log(a.length);', a: '3\n4', w: ['3\n3', '4\n4', '4\n3'],
  why: 'push добавляет элемент в конец и меняет сам массив, поэтому длина стала 4.' },
{ c: 'let x = 1;\n{\n  let x = 2;\n}\nconsole.log(x);', a: '1', w: ['2', 'undefined', 'null'],
  why: 'let живёт только внутри своих фигурных скобок. Внутренний x — другая переменная.' },
{ c: 'console.log([1, 2, 3].map(x => x * 2));', a: '[2, 4, 6]', w: ['[1, 2, 3]', '[2, 4]', '12'],
  why: 'map создаёт новый массив той же длины: каждый элемент превращается по правилу.' },
{ c: 'console.log([1, 2, 3, 4].filter(n => n % 2));', a: '[1, 3]', w: ['[2, 4]', '[1, 0, 1, 0]', '[true, false, true, false]'],
  why: 'filter смотрит, "правдивый" ли результат. У нечётных n % 2 даёт 1 (правда), у чётных — 0 (ложь).' },
{ c: 'const user = { name: "Аня" };\nuser.age = 25;\nconsole.log(user.age);', a: '25', w: ['undefined', 'null', 'Ошибка: const'],
  why: 'const запрещает заменить саму переменную, но содержимое объекта менять можно.' },
{ c: 'console.log(1 < 2 < 3);\nconsole.log(3 > 2 > 1);', a: 'true\nfalse', w: ['true\ntrue', 'false\nfalse', 'false\ntrue'],
  why: 'Сравнения считаются слева направо. 3 > 2 даёт true, а потом true > 1 превращается в 1 > 1 — это false.' },
{ c: 'console.log(Number("abc"));', a: 'NaN', w: ['0', 'undefined', 'null'],
  why: 'NaN значит "не число" — так JS отвечает, когда превратить значение в число не получилось.' },
{ c: 'console.log(NaN === NaN);', a: 'false', w: ['true', 'NaN', 'undefined'],
  why: 'NaN — единственное значение, которое не равно даже самому себе. Проверять нужно через Number.isNaN(x).' },
{ c: 'function f() {\n  return\n  42;\n}\nconsole.log(f());', a: 'undefined', w: ['42', 'null', '0'],
  why: 'JS сам ставит точку с запятой после return, если значение на следующей строке. Пиши return и значение в одной строке.' },
{ c: 'console.log(typeof [], Array.isArray([]));', a: 'object true', w: ['array true', 'object false', 'array false'],
  why: 'Для JS массив — особый объект. Отличить его от обычного объекта помогает Array.isArray.' },
{ c: 'const a = "5";\nconst b = 5;\nconsole.log(a == b, a === b);', a: 'true false', w: ['true true', 'false false', 'false true'],
  why: '== приводит типы и считает "5" и 5 равными, а === сравнивает ещё и тип. Всегда используй ===.' },
{ c: 'const arr = [10, 20, 30];\nconsole.log(arr[arr.length]);', a: 'undefined', w: ['30', '20', 'null'],
  why: 'Индексы идут с нуля: последний элемент — arr[2]. Индекса 3 нет, поэтому undefined.' },
{ c: 'console.log("b" + "a" + +"a" + "a");', a: 'baNaNa', w: ['baaa', 'ba0a', 'baa'],
  why: 'Унарный плюс +"a" пытается сделать из буквы число и получает NaN, а потом всё склеивается в строку.' },
{ c: 'var fns = [];\nfor (var i = 0; i < 3; i++) {\n  fns.push(() => i);\n}\nconsole.log(fns[0](), fns[1](), fns[2]());', a: '3 3 3', w: ['0 1 2', '2 2 2', 'undefined undefined undefined'],
  why: 'var не создаёт новую переменную на каждом шаге цикла, она одна на всех. К моменту вызова i уже равна 3. С let каждый шаг получил бы свою i.' },
{ c: 'const s = "Привет";\nconsole.log(s.toUpperCase(), s.length);', a: 'ПРИВЕТ 6', w: ['Привет 6', 'ПРИВЕТ 5', 'привет 6'],
  why: 'toUpperCase возвращает новую строку в верхнем регистре, length — количество символов.' },
{ c: 'console.log([..."abc"].reverse().join(""));', a: 'cba', w: ['abc', 'a,b,c', 'c,b,a'],
  why: 'Троеточие разворачивает строку в массив букв, reverse переворачивает его, join("") склеивает без разделителя.' },
{ c: 'console.log(2 ** 3, 7 % 3, Math.floor(-1.5));', a: '8 1 -2', w: ['6 1 -1', '8 2 -1', '8 1 -1'],
  why: '** — степень. % — остаток. Math.floor округляет вниз, а "вниз" для -1.5 это -2.' },
{ c: 'console.log([1, 2, 3].includes("2"));', a: 'false', w: ['true', '"2"', 'undefined'],
  why: 'includes сравнивает строго, как ===. Число 2 и строка "2" разные.' },
{ c: 'const o = { a: 1, b: 2 };\nconsole.log(Object.keys(o).length);', a: '2', w: ['1', '3', 'undefined'],
  why: 'Object.keys возвращает массив ключей ["a", "b"], а у массива есть length.' },
{ c: 'console.log(null ?? "по умолчанию", 0 || "x", 0 ?? "x");', a: 'по умолчанию x 0', w: ['null x x', 'по умолчанию 0 0', 'по умолчанию x x'],
  why: '?? подставляет запасное значение только для null и undefined. || подставляет его для любой "лжи", включая 0.' }
],

/* ───────── 2. Найди баг ─────────
   lines — строки кода, bug — номер(а) строки с ошибкой (с нуля, первый — главный), fix — как исправить */
bugs: [
{ lines: ['function sum(a, b) {', '  a + b;', '}', 'console.log(sum(2, 3));'], bug: [1], fix: 'return a + b;',
  why: 'Без return функция ничего не отдаёт наружу, поэтому вернётся undefined.' },
{ lines: ['const lives = 3;', 'lives = lives - 1;', 'console.log(lives);'], bug: [0, 1], fix: 'let lives = 3;',
  why: 'const нельзя переприсвоить. Если значение должно меняться, объявляй его через let.' },
{ lines: ['let age = 20;', 'if (age = 18) {', '  console.log("Ровно 18");', '}'], bug: [1], fix: 'if (age === 18) {',
  why: 'Один знак = присваивает, а не сравнивает. Такое условие всегда истинно и ещё портит переменную.' },
{ lines: ['const items = ["a", "b", "c"];', 'for (let i = 0; i <= items.length; i++) {', '  console.log(items[i]);', '}'], bug: [1], fix: 'i < items.length',
  why: 'Индексы идут от 0 до length - 1. С <= цикл сделает лишний шаг и напечатает undefined.' },
{ lines: ['let i = 0;', 'while (i < 5) {', '  console.log(i);', '}'], bug: [2, 1], fix: 'добавить i++ внутрь цикла',
  why: 'i не меняется, условие навсегда остаётся истинным, и цикл бесконечный.' },
{ lines: ['const names = ["Аня", "Макс"];', 'console.log(names.lenght);'], bug: [1], fix: 'names.length',
  why: 'Опечатка в слове length. JS не ругнётся, просто вернёт undefined — такие баги самые коварные.' },
{ lines: ['const user = { name: "Аня" };', 'console.log(user.Name);'], bug: [1], fix: 'user.name',
  why: 'Регистр важен: Name и name — разные ключи. Вторая вернёт undefined.' },
{ lines: ['function hello() {', '  return "Привет";', '}', 'console.log(hello);'], bug: [3], fix: 'console.log(hello());',
  why: 'Без круглых скобок функция не вызывается, мы печатаем саму функцию.' },
{ lines: ['const nums = [1, 2, 3];', 'const doubled = nums.map(n => { n * 2 });', 'console.log(doubled);'], bug: [1], fix: 'nums.map(n => n * 2)',
  why: 'Если в стрелочной функции есть фигурные скобки, нужен явный return. Иначе получится [undefined, undefined, undefined].' },
{ lines: ['const price = "100";', 'const total = price + 50;', 'console.log(total); // ждали 150'], bug: [1], fix: 'Number(price) + 50',
  why: 'Строка + число = склейка. Получится "10050". Сначала преврати строку в число.' },
{ lines: ['function test() {', '  const secret = 42;', '}', 'test();', 'console.log(secret);'], bug: [4], fix: 'secret видна только внутри test()',
  why: 'Переменная, объявленная внутри функции, снаружи не существует. Верни её через return.' },
{ lines: ['let total = 0;', '[1, 2, 3].forEach(n => total + n);', 'console.log(total);'], bug: [1], fix: 'total += n',
  why: 'Выражение total + n считается и тут же выбрасывается: никто не записал результат обратно в total.' },
{ lines: ['const text = "hello";', 'text.toUpperCase();', 'console.log(text);'], bug: [1], fix: 'const big = text.toUpperCase();',
  why: 'Строки неизменяемы. Метод возвращает новую строку, и её надо куда-то сохранить.' },
{ lines: ['function firstEven(nums) {', '  for (const n of nums) {', '    if (n % 2 === 0) return n;', '    else return null;', '  }', '}'], bug: [3], fix: 'убрать else return null',
  why: 'Если первое число нечётное, функция тут же выходит и остальные числа вообще не проверяются.' }
],

/* ───────── 3. Собери код ─────────
   lines — правильный порядок, out — что должен вывести собранный код (проверяется запуском) */
assemble: [
{ t: 'Функция складывает два числа. Выведи 5.', lines: ['function add(a, b) {', '  return a + b;', '}', 'console.log(add(2, 3));'], out: '5',
  why: 'Сначала объявляем функцию, потом вызываем её и печатаем результат.' },
{ t: 'Посчитай сумму чисел от 1 до 4. Выведи 10.', lines: ['let total = 0;', 'for (let i = 1; i <= 4; i++) {', '  total += i;', '}', 'console.log(total);'], out: '10',
  why: 'Накопитель заводим до цикла, меняем внутри, печатаем после цикла.' },
{ t: 'Оставь только чётные числа и выведи, сколько их.', lines: ['const nums = [1, 2, 3, 4];', 'const evens = nums.filter(n => n % 2 === 0);', 'console.log(evens.length);'], out: '2',
  why: 'Данные, потом обработка, потом вывод.' },
{ t: 'Повысь возраст и выведи "Аня: 26".', lines: ['const user = { name: "Аня", age: 25 };', 'user.age = 26;', 'console.log(user.name + ": " + user.age);'], out: 'Аня: 26',
  why: 'Печатать надо после изменения, иначе покажется старый возраст.' },
{ t: 'Функция проверки чётности. Выведи true, потом false.', lines: ['function isEven(n) {', '  return n % 2 === 0;', '}', 'console.log(isEven(4));', 'console.log(isEven(7));'], out: 'true\nfalse',
  why: 'Функция возвращает boolean: 4 чётное, 7 нет.' },
{ t: 'Повтори слово три раза. Выведи "jsjsjs".', lines: ['const word = "js";', 'const repeated = word.repeat(3);', 'console.log(repeated);'], out: 'jsjsjs',
  why: 'repeat возвращает новую строку, её сохраняем и печатаем.' },
{ t: 'Оценка по баллам. Выведи "A" для 95.', lines: ['function grade(score) {', '  if (score >= 90) {', '    return "A";', '  }', '  return "B";', '}', 'console.log(grade(95));'], out: 'A',
  why: 'Внутри функции: условие с ранним return, а запасной вариант идёт после него.' },
{ t: 'Склей буквы из массива в одну строку. Выведи "abc".', lines: ['const items = ["a", "b", "c"];', 'let result = "";', 'for (const item of items) {', '  result += item;', '}', 'console.log(result);'], out: 'abc',
  why: 'Опять накопитель: пустая строка до цикла, дописываем в цикле, печатаем в конце.' },
{ t: 'Обратный отсчёт: 3, 2, 1.', lines: ['let n = 3;', 'while (n > 0) {', '  console.log(n);', '  n--;', '}'], out: '3\n2\n1',
  why: 'Внутри цикла сначала печатаем, потом уменьшаем n, иначе цикл не остановится.' },
{ t: 'Сложи цены через reduce. Выведи 400.', lines: ['const prices = [100, 250, 50];', 'const total = prices.reduce((sum, p) => sum + p, 0);', 'console.log(total);'], out: '400',
  why: 'reduce сворачивает массив в одно значение, стартуя с 0.' }
],

/* ───────── 4. Заполни пропуск ─────────
   t — задача, c — код с ___, o — варианты, a — правильный, out — вывод с правильным ответом */
gaps: [
{ t: 'Удвоить каждое число', c: 'const nums = [1, 2, 3];\nconst doubled = nums.___(n => n * 2);\nconsole.log(doubled);', o: ['map', 'filter', 'forEach', 'reduce'], a: 'map', out: '[2, 4, 6]',
  why: 'map превращает каждый элемент. forEach ничего не возвращает, а filter только отбирает.' },
{ t: 'Проверить, что число нечётное', c: 'const n = 7;\nif (n ___ 2 === 1) {\n  console.log("нечётное");\n}', o: ['%', '/', '*', '-'], a: '%', out: 'нечётное',
  why: '% даёт остаток от деления. У нечётных чисел остаток от деления на 2 равен 1.' },
{ t: 'Перевести строку в верхний регистр', c: 'const s = "js";\nconsole.log(s.___());', o: ['toUpperCase', 'toUppercase', 'upper', 'capitalize'], a: 'toUpperCase', out: 'JS',
  why: 'Названия в JS пишутся в camelCase: слитно, каждое следующее слово с большой буквы.' },
{ t: 'Достать поле объекта', c: 'const user = { name: "Аня", age: 25 };\nconsole.log(user___name);', o: ['.', ':', '->', '::'], a: '.', out: 'Аня',
  why: 'Доступ к полю объекта идёт через точку: user.name.' },
{ t: 'Повторять, пока i меньше 3', c: 'let i = 0;\n___ (i < 3) {\n  i++;\n}\nconsole.log(i);', o: ['while', 'if', 'for', 'loop'], a: 'while', out: '3',
  why: 'while повторяет блок, пока условие истинно. if выполнил бы блок только один раз.' },
{ t: 'Добавить элемент в конец массива', c: 'const fruits = ["яблоко", "банан"];\nfruits.___("груша");\nconsole.log(fruits.length);', o: ['push', 'add', 'append', 'concat'], a: 'push', out: '3',
  why: 'push меняет сам массив. concat вернул бы новый массив, а исходный остался бы прежним.' },
{ t: 'Вернуть результат из функции', c: 'function square(x) {\n  ___ x * x;\n}\nconsole.log(square(4));', o: ['return', 'print', 'yield', 'give'], a: 'return', out: '16',
  why: 'return отдаёт значение тому, кто вызвал функцию.' },
{ t: 'Сравнить строго, чтобы результат был false', c: 'const same = 5 ___ "5";\nconsole.log(same);', o: ['===', '==', '=', '!=='], a: '===', out: 'false',
  why: '=== сравнивает и значение, и тип: число 5 и строка "5" не равны.' },
{ t: 'Оставить только числа больше 6', c: 'const nums = [5, 8, 12];\nconst big = nums.___(n => n > 6);\nconsole.log(big);', o: ['filter', 'map', 'find', 'some'], a: 'filter', out: '[8, 12]',
  why: 'filter возвращает массив подходящих. find вернул бы только первый, some просто true/false.' },
{ t: 'Найти первое число больше 6', c: 'const nums = [5, 8, 12];\nconst first = nums.___(n => n > 6);\nconsole.log(first);', o: ['find', 'filter', 'includes', 'indexOf'], a: 'find', out: '8',
  why: 'find возвращает первый подходящий элемент (а не массив).' },
{ t: 'Разбить строку по запятой на массив', c: 'const text = "a,b,c";\nconst parts = text.___(",");\nconsole.log(parts.length);', o: ['split', 'join', 'slice', 'replace'], a: 'split', out: '3',
  why: 'split режет строку на части, а join — наоборот, склеивает массив в строку.' },
{ t: 'Поменять a и b местами', c: 'let a = 1, b = 2;\n[a, b] = [___];\nconsole.log(a, b);', o: ['b, a', 'a, b', 'b, b', 'a, a'], a: 'b, a', out: '2 1',
  why: 'Деструктуризация: справа собирается новый массив [2, 1], слева он раскладывается обратно в a и b.' },
{ t: 'Не упасть, если address нет', c: 'const user = { name: "Аня" };\nconsole.log(user.address___city);', o: ['?.', '.', '??', '||'], a: '?.', out: 'undefined',
  why: 'Опциональная цепочка ?. останавливается и возвращает undefined, если слева пусто. Без неё получилась бы ошибка.' },
{ t: 'Оставить 0, а не заменить его на 10', c: 'const count = 0;\nconsole.log(count ___ 10);', o: ['??', '||', '+', '-'], a: '??', out: '0',
  why: '?? подставляет запасное только для null и undefined. || заменил бы и 0.' },
{ t: 'Сложить все числа в одно', c: 'const total = [1, 2, 3].___((sum, n) => sum + n, 0);\nconsole.log(total);', o: ['reduce', 'map', 'filter', 'forEach'], a: 'reduce', out: '6',
  why: 'reduce сворачивает массив в одно значение, начиная со второго аргумента (0).' },
{ t: 'Значение по умолчанию "друг"', c: 'function hello(name = ___) {\n  return "Привет, " + name;\n}\nconsole.log(hello());', o: ['"друг"', 'друг', 'name', 'null'], a: '"друг"', out: 'Привет, друг',
  why: 'Текст нужно взять в кавычки, иначе JS решит, что это имя переменной.' },
{ t: 'Отсортировать числа по возрастанию', c: 'const nums = [3, 1, 2];\nnums.___((a, b) => a - b);\nconsole.log(nums);', o: ['sort', 'reverse', 'map', 'filter'], a: 'sort', out: '[1, 2, 3]',
  why: 'sort меняет массив на месте. Без функции сравнения он сортирует как строки.' },
{ t: 'Вывести последнюю букву', c: 'const word = "привет";\nconsole.log(word[___]);', o: ['word.length - 1', 'word.length', '-1', 'word.last'], a: 'word.length - 1', out: 'т',
  why: 'Индексы с нуля, поэтому последний — length - 1.' },
{ t: 'Перебрать ключи объекта', c: 'const obj = { a: 1, b: 2 };\nfor (const key ___ obj) {\n  console.log(key);\n}', o: ['in', 'of', 'at', 'each'], a: 'in', out: 'a\nb',
  why: 'for…in перебирает ключи объекта, а for…of перебирает значения массивов и других перебираемых вещей.' },
{ t: 'Сделать копию массива', c: 'const arr = [1, 2, 3];\nconst copy = [___arr];\ncopy.push(4);\nconsole.log(arr.length);', o: ['...', '&', '*', '..'], a: '...', out: '3',
  why: 'Троеточие (spread) раскладывает элементы в новый массив. Исходный не пострадает.' }
],

/* ───────── 5. Тип-блиц ─────────
   e — выражение, a — что вернёт typeof */
types: [
{ e: '"привет"', a: 'string', why: 'Текст в кавычках — string.' },
{ e: '42', a: 'number', why: 'Все числа (целые и дробные) — number.' },
{ e: 'true', a: 'boolean', why: 'true и false — boolean.' },
{ e: 'undefined', a: 'undefined', why: 'У undefined свой тип.' },
{ e: 'null', a: 'object', why: 'Знаменитая ошибка языка: typeof null === "object".' },
{ e: '[]', a: 'object', why: 'Массив — это особый объект. Проверять нужно Array.isArray.' },
{ e: '{}', a: 'object', why: 'Обычный объект.' },
{ e: 'NaN', a: 'number', why: 'NaN значит "не число", но по типу это number.' },
{ e: '() => {}', a: 'function', why: 'Функции имеют отдельный тип function.' },
{ e: 'Symbol("id")', a: 'symbol', why: 'Symbol — уникальный идентификатор.' },
{ e: '10n', a: 'bigint', why: 'Буква n делает число BigInt — для очень больших чисел.' },
{ e: '"5" * 2', a: 'number', why: 'Умножение превращает строку в число: 10.' },
{ e: '"5" + 2', a: 'string', why: 'Плюс со строкой склеивает: "52".' },
{ e: '[1, 2].length', a: 'number', why: 'length — число.' },
{ e: 'typeof 1', a: 'string', why: 'Сам typeof возвращает строку: "number".' },
{ e: '!!"0"', a: 'boolean', why: 'Двойное отрицание превращает значение в boolean. Строка "0" непустая, значит true.' },
{ e: 'new Date()', a: 'object', why: 'Дата — объект.' },
{ e: 'Infinity', a: 'number', why: 'Бесконечность — тоже number.' },
{ e: '[] + []', a: 'string', why: 'Плюс превращает массивы в строки (пустые), получается пустая строка.' },
{ e: 'undefined + 1', a: 'number', why: 'Получится NaN, а он number.' },
{ e: 'null + 1', a: 'number', why: 'null превращается в 0, получается 1.' },
{ e: 'parseInt("12px")', a: 'number', why: 'parseInt читает цифры с начала строки: 12.' },
{ e: 'String(123)', a: 'string', why: 'String() превращает значение в строку.' },
{ e: 'void 0', a: 'undefined', why: 'void всегда возвращает undefined.' },
{ e: '/abc/', a: 'object', why: 'Регулярное выражение — объект.' },
{ e: 'class A {}', a: 'function', why: 'Класс в JS — это функция под капотом.' },
{ e: 'Math', a: 'object', why: 'Math — объект с функциями и константами.' },
{ e: 'Math.max', a: 'function', why: 'Math.max — функция.' },
{ e: 'JSON.stringify({})', a: 'string', why: 'JSON.stringify превращает данные в строку: "{}".' }
]
};
